function curTable=createPhysSigTable(desc)

names={'time';'RA';'LA';'LL';'V1';'V2';'V3';'leadI';'leadII';'leadIII';... 
    'afRA';'afLA';'afLL';'afV1';'afV2';'afV3';... 
    'afleadI';'afleadII';'afleadIII'; ... 
    'IBP1';'IBP2';'X';'Y';'Z';... 
    'OrigFilename';'Comment';'Fs';...
    };
curTable=array2table(zeros(1,numel(names)));
curTable.Properties.VariableNames=names;
curTable.Properties.Description=desc;
curTable.Properties.VariableDescriptions=... 
    {... 
    'Time vector for all data sets',... 
    'Right Arm electrode data, prior to adaptive filter',... 
    'Left Arm electrode data, prior to adaptive filter', ...
    'Left Leg electrode data, prior to adaptive filter', ...
    'V1 electrode data, prior to adaptive filter', ...
    'V2 electrode data, prior to adaptive filter', ...
    'V3 electrode data, prior to adaptive filter', ...
    'leadI electrode data, prior to adaptive filter,calculated in software', ...
    'leadII electrode data, prior to adaptive filter,calculated in software', ...
    'leadIII electrode data, prior to adaptive filter,calculated in software', ...
    'Right Arm electrode data, after adaptive filter',... 
    'Left Arm electrode data, after adaptive filter', ...
    'Left Leg electrode data, after adaptive filter', ...
    'V1 electrode data, after adaptive filter', ...
    'V2 electrode data, after adaptive filter', ...
    'V3 electrode data, after adaptive filter', ...
    'leadI electrode data, after adaptive filter,calculated in software', ...
    'leadII electrode data, after adaptive filter,calculated in software', ...
    'leadIII electrode data, after adaptive filter,calculated in software', ...
    'First channel of Invasive Blood Pressure',... 
    'Second channel of Invasive Blood Pressure',... 
    'X gradient signals as acquired from the MRI control signal, after low pass filtering',... 
    'Y gradient signals as acquired from the MRI control signal, after low pass filtering',... 
    'Z gradient signals as acquired from the MRI control signal, after low pass filtering',... 
    'Original filename for imported data',...
    'Optional comment for dataset',... 
    'Sample rate of data'...
    };
curTable.Properties.VariableUnits=... 
    {... 
    'seconds',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    'ADC counts',... 
    '',...
    '',...
    'Samples per sec'...
    };
%delete the dummy data
curTable(1,:)=[];