function tbl=runAnalysis(tbl,otherScans)


%% Calculate gradient power
tbl.gradPower=rowfun(@bandpower,tbl,... 
            'InputVariable','gradientSum',... 
            'ExtractCellContents',true,'OutputFormat','uniform');

%% calculate power of out-of-bore signal
tbl.OutOfBorePower=rowfun(@bandpower,tbl,... 
    'InputVariables',{'outOfBore'},... 
    'ExtractCellContents',true,'OutputFormat','uniform');

%% calculate power of in-bore signal
tbl.inBorePower=rowfun(@bandpower,tbl,... 
    'InputVariables',{'inBore'},... 
    'ExtractCellContents',true,'OutputFormat','uniform');

%% calculate power of rtScanPreAF signal
tbl.preAFPower=rowfun(@bandpower,tbl,... 
    'InputVariables',{'rtScanPreAF'},... 
    'ExtractCellContents',true,'OutputFormat','uniform');

%% calculate power of rtScanPostAF signal as a baseline
tbl.postAFPower=rowfun(@bandpower,tbl,... 
    'InputVariables',{'rtScanPostAF'},... 
    'ExtractCellContents',true,'OutputFormat','uniform');
%% calculate difference of pre- and post-AF scans
tbl.afDiff=rowfun(@minus,tbl,... 
    'InputVariables',{'rtScanPreAF','rtScanPostAF'},... 
    'ExtractCellContents',true,'OutputFormat','cell');

%% calculate power of difference between pre and post AF filtering
tbl.afDiffPower=rowfun(@bandpower,tbl,... 
    'InputVariables',{'afDiff'},... 
    'ExtractCellContents',true,'OutputFormat','uniform');

%% Calculate SNR using inBore as ideal signal and diff signal as noise
tbl.SNR=rowfun(@snr,tbl,... 
    'InputVariables',{'inBore','afDiff'},... 
    'ExtractCellContents',true,'OutputFormat','uniform');

%% Calculate SNR using inBore as ideal signal and diff signal as noise
tbl.SNRpreAF=rowfun(@snr,tbl,... 
    'InputVariables',{'rtScanPreAF','afDiff'},... 
    'ExtractCellContents',true,'OutputFormat','uniform');

%% Calculate SNR using inBore as ideal signal and diff signal as noise
tbl.SNRpostAF=rowfun(@snr,tbl,... 
    'InputVariables',{'rtScanPostAF','afDiff'},... 
    'ExtractCellContents',true,'OutputFormat','uniform');

%% Find number of ECG peaks and compare with possible noise peaks
getRpks=@(o,i,pre,post) getRPeaks(o,i,pre,post,'showPlot',false);
rpks=rowfun(getRpks,tbl,... 
    'InputVariables',{'outOfBore','inBore','rtScanPreAF','rtScanPostAF'},...
    'ExtractCellContents',true,'OutputFormat','table',... 
    'OutputVariableNames',{'RPks_preAF','RPks_postAF'});

getNpks=@(pre,post,grad) getNoisePeaks(pre,post,grad,'showPlot',false);
npks=rowfun(getNpks,tbl,...
    'InputVariables',{'rtScanPreAF','rtScanPostAF','gradientSum'},...
    'ExtractCellContents',true,'OutputFormat','table',... 
    'OutputVariableNames',{'NoisePks_preAF','NoisePks_postAF','gradientPeaks'});

%% anon function to remove R peaks from noise peaks
function y=delRpk(x,y) 
    idx=ismembertol(y,x,5,'DataScale',20);
    if (~isempty(idx))
        y(idx)=[];
    end
end
tbl=[tbl rpks npks];
tbl.NoisePks_preAF=... 
    rowfun(@delRpk,tbl,... 
            'InputVariable',{'RPks_postAF','NoisePks_preAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');

tbl.NoisePks_postAF=... 
    rowfun(@delRpk,tbl,... 
            'InputVariable',{'RPks_postAF','NoisePks_postAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');        

    
function ht=peakHt(x,locs)
    mm=movmean(x,101);
    ht=abs(x(locs)-mm(locs));
end

tbl.RPksHeight_preAF=... 
    rowfun(@peakHt,tbl,... 
            'InputVariable',{'rtScanPreAF','RPks_preAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');
        
tbl.RPksHeight_postAF=...
    rowfun(@peakHt,tbl,... 
            'InputVariable',{'rtScanPostAF','RPks_postAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');
        
tbl.NoisePksHeight_preAF=... 
    rowfun(@peakHt,tbl,... 
            'InputVariable',{'rtScanPreAF','NoisePks_preAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');
        
tbl.NoisePksHeight_postAF=...
    rowfun(@peakHt,tbl,... 
            'InputVariable',{'rtScanPostAF','NoisePks_postAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');
   
tbl.MaxNoisePks_preAF=... 
    rowfun(@max,tbl,... 
            'InputVariable',{'NoisePksHeight_preAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');
tbl.MaxNoisePks_postAF=... 
    rowfun(@max,tbl,... 
            'InputVariable',{'NoisePksHeight_postAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');

tbl.MeanRpks_preAF=... 
    rowfun(@mean,tbl,... 
            'InputVariable',{'RPksHeight_preAF'},... 
            'ExtractCellContents',true,'OutputFormat','uniform');
tbl.MeanRpks_postAF=... 
    rowfun(@mean,tbl,... 
            'InputVariable',{'RPksHeight_postAF'},... 
            'ExtractCellContents',true,'OutputFormat','uniform');
        
tbl.MeanNoisePks_preAF=... 
    rowfun(@mean,tbl,... 
            'InputVariable',{'NoisePksHeight_preAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');
tbl.MeanNoisePks_postAF=... 
    rowfun(@mean,tbl,... 
            'InputVariable',{'NoisePksHeight_postAF'},... 
            'ExtractCellContents',true,'OutputFormat','cell');
        
        
%% Plots
genPaperPlots(tbl,otherScans);



end %runAnalysis